name: Artifact Release Upload

on:
  push:
    branches:
      - feature/*

env:
  APP_NAME: picker_wheel

jobs:
  build-macos:
    permissions:
      contents: write
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: '3.19.0'
          cache: true
          cache-sdk: true
      - name: Install dependencies
        run: flutter pub get
      # - name: Run tests (optional)
      #   run: flutter test
      - name: Build App
        run: |
            flutter build macos --release
            zip picker_wheel_macos_intel.zip ./build/macos/Build/Products/Release/picker_wheel.app
      - uses: actions/upload-artifact@v4
        with:
          path: picker_wheel_macos_intel.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CI_CD }}
        